version: "3"

networks:
  asvsp:
    name: asvsp
    external: true

services:
  postgres-hue-db:
    image: postgres:latest
    container_name: postgres-hue-db
    restart: always
    environment:
      - POSTGRES_USER=hue
      - POSTGRES_PASSWORD=hue
    ports:
      - "5432:5432"
    volumes:
      - postgres-hue-db-volume:/var/lib/postgresql/data
    networks:
      - asvsp

  hue:
    # image: gethue/hue:latest
    build: .
    container_name: hue
    hostname: hue
    dns: 8.8.8.8
    ports:
      - "8888:8888"
    # bind mount config (not working on all OS problems with permission)
    # volumes:
      # - ./config:/usr/share/hue/desktop/conf
    depends_on:
      - postgres-hue-db
    networks:
      - asvsp

volumes:
  postgres-hue-db-volume: